apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tg6or7184-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tg6or7184-go 
  name: tg6or7184-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tg6or7184-go 
